name: Fetch JSON Updates
on:
  schedule:
    # run once a day
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Checkout Main
        run: |
          git fetch origin
          git branch -f main origin/main

      - name: Setup
        uses: ./.github/actions/setup

      - name: Fetch
        run: ./scripts/update-data.sh
